export type LogCategoryLiteral =
  | 'DAMAGED'
  | 'DESTROYED'
  | 'EQUIPPED'
  | 'UNEQUIPPED'
  | 'CHECK'
  | 'CONSUMED'
  | 'HEALED'
  | 'ATTACKED'
  | 'FREE'
  | 'EQUIP-ERROR'
  | 'TOOK'
  | 'SCENE'
  | 'MISSED'
  | 'DIED'
  | 'LOST';
