export type LogCategoryLiteral =
  | 'EQUIPPED'
  | 'UNEQUIPPED'
  | 'CHECK'
  | 'CONSUMED'
  | 'ATTACKED'
  | 'FREE'
  | 'EQUIP-ERROR'
  | 'TOOK'
  | 'SCENE'
  | 'MISSED'
  | 'DIED'
  | 'LOST'
  | 'NOT-FOUND'
  | 'OPENED';
