export type SkillNameLiteral =
  | 'Athleticism'
  | 'Appraise'
  | 'Artillery (Siege)'
  | 'Artillery (War)'
  | 'Bargain'
  | 'Brawl'
  | 'Craft (Blacksmithing)'
  | 'Craft (Cooking)'
  | 'Craft (Leatherworking)'
  | 'Craft (Woodworking)'
  | 'Craft (Sewing)'
  | 'Demolition'
  | 'Dodge'
  | 'Disguise'
  | 'Drive (Automobile)'
  | 'Drive (Traction)'
  | 'Drive (Heavy Vehicles)'
  | 'Etiquette'
  | 'Firearm (Handgun)'
  | 'Firearm (Shooter)'
  | 'First Aid'
  | 'Gaming'
  | 'Industrial Heavy Machinery'
  | 'Hide'
  | 'Insight'
  | 'Knowledge (Antique)'
  | 'Knowledge (History)'
  | 'Knowledge (Linguistics)'
  | 'Knowledge (Occult)'
  | 'Knowledge (Religion)'
  | 'Knowledge (Strategy)'
  | 'Listen'
  | 'Melee Weapon (Simple)'
  | 'Melee Weapon (Great)'
  | 'Ranged Weapon (Bow)'
  | 'Ranged Weapon (Throw)'
  | 'Navigate'
  | 'Performance'
  | 'Persuade'
  | 'Pilot (Airplane)'
  | 'Pilot (Boat)'
  | 'Research'
  | 'Ride (Horse)'
  | 'Science(Botany)'
  | 'Science(Chemistry)'
  | 'Science(Medicine)'
  | 'Science(Mathematics)'
  | 'Science(Physics)'
  | 'Sleight of Hand'
  | 'Spot'
  | 'Survival'
  | 'Engineering (Computer)'
  | 'Engineering (Electrical)'
  | 'Engineering (Mechanical)'
  | 'Throw'
  | 'Track';
